version: "3.9"

services:
  db:  # service name for database
    image: postgres:14
    container_name: db_container  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workout_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Store data even if container is removed
    ports:
      - "5432:5432"  # Make the DB accessible to the local machine

volumes:
  postgres_data:  # Volume declaration for persistent data
